### ISSUE TITLE
Change "Direct Messages" button size

### ISSUE THREAD

**Issue by LolnationCH** [WhatDaPuck/NotAnotherAnimeTheme#10]
How can I change the size of the "Direct Messages" button?
I found your .css with the mention 
> /* DONT TOUCH ANYTHING HERE UNLESS YOU REALLY KNOW WHAT YOU'RE DOING */
```
[class~=guilds-wrapper] [class~=guilds] [class~=friends-icon] {
    width: 37.5pt;
}
[class~=guilds-wrapper] [class~=guilds] [class~=friends-icon],
[class~=guilds-wrapper] [class~=guilds] [class~=guild] {
    height: 3.125pc;
}
```

adding those line (with a width modified of course) to the .css provided in the readme have been unsuccessful. Adding the whole file import makes the .css invisble in the theme window on Discord.

I want to make the button as large as the column with maybe a margin of 5 px left and right.

**Comment by WhatDaPuck** [comment]
The best thing to do would be to add your modified code to the .theme.css file.  The regular .css file isn't loaded locally.  It is loaded from a CDN when you load the theme, from line 2 in the .theme.css file [right here.](https://github.com/WhatDaPuck/NotAnotherAnimeTheme/blob/master/NotAnotherAnimeTheme.theme.css#L2)

If you were to add your code to the bottom of the .theme.css file then it should overwrite the loaded CDN code.  Try that and if it doesn't work feel free to message me.
