### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by Braydenpiag** [WhatDaPuck/NotAnotherAnimeTheme#11]
I placed the .css file into the Themes folder, and it's not showing up when i go to the themes section in the BetterDiscord app. I'm sure that i'm doing something wrong, since i'm new to Github though.

**Comment by WhatDaPuck** [comment]
use this file instead https://github.com/WhatDaPuck/NotAnotherAnimeTheme/blob/master/NotAnotherAnimeTheme.theme.css


you want the .theme.css file.  not the .css file

**Comment by Braydenpiag** [comment]
I'm sure you're about to facepalm as you read this, but uh... How do i download that specific file?

**Comment by WhatDaPuck** [comment]
https://raw.githubusercontent.com/WhatDaPuck/NotAnotherAnimeTheme/master/NotAnotherAnimeTheme.theme.css

open that link, right click, save as

**Comment by Braydenpiag** [comment]
![confusion](https://user-images.githubusercontent.com/35677732/35205936-110368de-ff07-11e7-82f4-6adc1c4b4441.JPG)

It's still not showing up, Hmm..

**Comment by WhatDaPuck** [comment]
are you sure you're placing it in the right directory?  click the "Open Theme Folder" and see if it is in there.  If it isn't then place the file there

**Comment by Braydenpiag** [comment]
![confusion2](https://user-images.githubusercontent.com/35677732/35206004-838ae986-ff07-11e7-9c11-5a643e213df6.JPG 
It's in there, yeah.. I apolagize if i'm annoying you :/

**Comment by Braydenpiag** [comment]
Weird, link messed up

**Comment by WhatDaPuck** [comment]
did you fully restart discord after you placed the file in there?

**Comment by Braydenpiag** [comment]
And let the facepalms ensue....... no. Im sorry xD

**Comment by Braydenpiag** [comment]
It works now! thanks for responding though

**Comment by WhatDaPuck** [comment]
No problem.  I'm gonna close the issue.  If you have any other problems feel free to open another issue or message me on discord.

**Comment by Spinys** [comment]
not to be a bother or anything yeah but did you update the theme because the clouds image isnt showing up
