### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by DryNoodles** [WhatDaPuck/NotAnotherAnimeTheme#12]
First I want to say what an awesome theme this is, and I've really been enjoying it. The only question I had is whether or not it would be possible to change the colors of some things that aren't included in the downloaded css file. I noticed the original code has changed the color of these elements, but there's no option/input in the download for them. Just minor things, but I was curious if it were possible to change?

![discordcrop2](https://user-images.githubusercontent.com/29576324/35477143-1c1d9482-038b-11e8-8bed-dfaa419c6a68.png)

![discordcrop](https://user-images.githubusercontent.com/29576324/35477145-26886064-038b-11e8-95c3-0d661bb0d1e0.png)

Was wondering if you knew the classes for the blue highlighted @here text, green background highlight on users and blue background and text bubble for hovering your mouse over a server.  And again, awesome theme!

**Comment by WhatDaPuck** [comment]
Some of those you unfortunately can't change at all.  For example when you hover over a server that is unchangeable.  I'll expose some more elements when I get a chance too.  I'll comment on this thread again when I've added them.

**Comment by WhatDaPuck** [comment]
I've added more customizability over several commits.
