### ISSUE TITLE
XXX is typing...

### ISSUE THREAD

**Issue by minjinim** [WhatDaPuck/NotAnotherAnimeTheme#13]
It comes up as the orginial Discord colour
![immagine](https://user-images.githubusercontent.com/29446991/35773147-98f15fd4-0917-11e8-9cc4-d3c2200ea93d.png)

**Comment by WhatDaPuck** [comment]
fixed in this commit https://github.com/WhatDaPuck/NotAnotherAnimeTheme/commit/8f364ffea3a9fa0e18f4a97121f35d154af9c6cf
