### ISSUE TITLE
Certain unchangeable colors.

### ISSUE THREAD

**Issue by blxss** [WhatDaPuck/NotAnotherAnimeTheme#14]
I've been able to change all colors minus one. To clarify, everything's identified by # or RGBA, and I've gone through all 1,000+ of them and changed everything to how I personally want it, and this one color, won't come up anywhere...
 To clarify what colors, here's images;

![green1](https://user-images.githubusercontent.com/36357076/36072184-358404e0-0f13-11e8-846e-ef9183169cfb.png)

This is when hovering over a user.

![green2](https://user-images.githubusercontent.com/36357076/36072185-3778cf56-0f13-11e8-934b-22db3b685d9e.png)

The 'pro-tip' and green seperation line.

![green3](https://user-images.githubusercontent.com/36357076/36072186-38d8c842-0f13-11e8-98d1-dad8d9e87788.png)

The numbers next to the voice-chat.

Thanks! <3

**Comment by WhatDaPuck** [comment]
fixed in this commit https://github.com/WhatDaPuck/NotAnotherAnimeTheme/commit/4b24400d4ba16847e9b93e513469d51b3241f461
