### ISSUE TITLE
Transparent issue when clicking a profile pic

### ISSUE THREAD

**Issue by AloXado320** [WhatDaPuck/NotAnotherAnimeTheme#144]
![image](https://user-images.githubusercontent.com/38191089/67866915-a2ff0980-faf7-11e9-9daf-4e0138a19a82.png)

**Comment by ashergz** [comment]
Came here to report this myself. It just started happening for me for some reason. Was working perfectly fine like five minutes ago.

**Comment by puckzxz** [comment]
Some changes were made to the variables in the theme file
You can change the appearance by editing the `--user-popup-background` variable in the theme file
