### ISSUE TITLE
Couple parts left un-skinned.

### ISSUE THREAD

**Issue by Adyne** [WhatDaPuck/NotAnotherAnimeTheme#15]
Hey. I just downloaded the theme, it looks amazing, and I only have issues with some parts.

The guild and status menus are bright white (Turned it to the default color on the screenshot)
Every right-click menu.
And lastly the screenshotted part of the embed got left out.

I could make a PR to fix those in 10mins, but I have no idea which color to turn them into.
Anyways, pretty nice theme, keep it up!

![i8so4](https://user-images.githubusercontent.com/35479752/36126128-70ae0f62-1057-11e8-9f80-155ec5741038.png)
![jfffo](https://user-images.githubusercontent.com/35479752/36126142-7ccbb6f0-1057-11e8-8a05-028804bd83d1.png)
![0ngs3](https://user-images.githubusercontent.com/35479752/36126147-7f433c6e-1057-11e8-9674-2169cc0d4750.png)
![mil6g](https://user-images.githubusercontent.com/35479752/36126148-7f5fc938-1057-11e8-82e4-85eaf375aca2.png)
![o0fjw](https://user-images.githubusercontent.com/35479752/36126801-75dd902c-105a-11e8-9a91-71c20562057b.png)
![7h3gw](https://user-images.githubusercontent.com/35479752/36126802-75fd38d2-105a-11e8-8a74-657e81830056.png)

**Comment by WhatDaPuck** [comment]
fixed in this commit https://github.com/WhatDaPuck/NotAnotherAnimeTheme/commit/dd7486b115de8dba2e6ea6e90f00a68aad632e3f

**Comment by WhatDaPuck** [comment]
the embeds i don't want to change because those can change for different embedded content and it could mess things up.

**Comment by Adyne** [comment]
I see, Thanks for the quick fix!
-closed

**Comment by Adyne** [comment]
This one got left out ^^

![dy4kk](https://user-images.githubusercontent.com/35479752/36130090-0b82588c-106b-11e8-9e01-2f8f22197477.png)

**Comment by WhatDaPuck** [comment]
fixed in this commit https://github.com/WhatDaPuck/NotAnotherAnimeTheme/commit/48b857c70e46e233e5245e886092e16b882e4d93

cant change the dead server icon

**Comment by Adyne** [comment]
Thanks!
