### ISSUE TITLE
Misaligned Public Server Icon and Direct Messages

### ISSUE THREAD

**Issue by legosp7** [WhatDaPuck/NotAnotherAnimeTheme#16]
![ruhroh](https://user-images.githubusercontent.com/37090462/37007255-af91a7b4-2099-11e8-86d4-07d8d9253f6f.png)

So the problem is just a minor one, and I don't know if it's the theme or just BetterDiscord, but the public servers icon is cut off and misaligned.

**Comment by WhatDaPuck** [comment]
Go to your settings and then BetterDiscord->Core and disable "Public Servers"

![discord_2018-03-05_19-34-30](https://user-images.githubusercontent.com/10362744/37007661-6b82b280-20ac-11e8-8115-03dd203bbad0.png)

**Comment by legosp7** [comment]
Oh well that was easy, lmao. Thanks
