### ISSUE TITLE
Some things aren't skinned!

### ISSUE THREAD

**Issue by luxidoptera** [WhatDaPuck/NotAnotherAnimeTheme#25]
Hi there, I just downloaded this theme looking for an alternative to a theme I was using that recently broke. Unfortunately, this theme seems to have broken in the same way- it looks like Discord has updated the sidebar and such, and now a couple things aren't skinned correctly! The most noticeable issue is with the users sidebar itself, [which is now the default grey instead of being translucent](https://prnt.sc/j125c3), but I'm also seeing the same issue in right-click menus, [which appear to be only partially skinned.](http://prntscr.com/j125uh)

I may also want to mention that the options menu in Discord [is not skinned at all](http://prntscr.com/j126zb), but I don't know if it's supposed to be, so take that with a grain of salt.

I noticed some things were mentioned to be fixed in the latest commit, but I think I do have the latest commit and it's still a bit busted. (I dl'd the theme from the frontpage via downloading as ZIP so apologies if I'm just being dumb.) Would love to see this fixed soon!

**Comment by WhatDaPuck** [comment]
The CDN I use to deliver the theme takes a bit to update from the latest commit, usually a few hours. The sidebar is already fixed and the right click menus have been changing a lot recently and it seems that as soon as I fix them they break again.

**Comment by luxidoptera** [comment]
Oh, my apologies! Didn't realize that it was just things being slow to update. Thanks for telling me, I'll close the issue!

**Comment by Phatkez** [comment]
Sorry to reopen this! Looks like the links for the Single/Triple column variants are for v1.0 rather than v2.2 like the Double column default is. Am I being stupid here? Trying to get the single column variant up and running with the fixed side bar, but it's not playing ball.

Nice Ryuko ava btw.

**Comment by WhatDaPuck** [comment]
While I should, I haven't changed the version names in months.  They really don't matter.  As for the sidebar unfortunately the CDN I use still hasn't updated... One of the downsides of using a free CDN.
