### ISSUE TITLE
How to change transparency of the layer above the background?

### ISSUE THREAD

**Issue by hakuame** [WhatDaPuck/NotAnotherAnimeTheme#5]
The background is too dark. I don't know which rgba to change the transparency.

`/*THIS CHANGES THE EMBED BACKGROUND DARKNESS AND BORDER COLOR*/
.theme-dark .message-group .embed {
    background-color: rgba(0, 0, 0, 0.7);
    border-color: rgba(67, 181, 129, 0.2);
}`

I tried to change this code but it doesn't work.

**Comment by WhatDaPuck** [comment]
Sorry but could you post a screenshot of what you are wanting to change?

**Comment by hakuame** [comment]
![ss](https://i.imgur.com/FfmnGIi.png)

This is my previous theme. I changed the transparency so I can have my background brighter.
This is the GitHub page of this theme: [Crystalline-css](https://github.com/SamuiNe/Crystalline-css)

`.app, .connecting {
    /* You can adjust the background brightness by reducing the fourth value of below.
       0.0 for no dark background, 1.0 for full darkness.
       Or, you can change the other values for tint and so.
       1st value - Red 0-255
       2nd value - Green 0-255
       3rd value - Blue 0-255
       4th value - Alpha (Opacity) 0.0-1.0 */
    background: rgba(0, 0, 0, 0.8);

    -webkit-transition: background 0.5s ease-in-out;
    transition: background 0.5s ease-in-out;
}`

**Comment by WhatDaPuck** [comment]
Unfortunately there isn't a way to currently.  Give me a bit so I can expose all the code to be able to change it.  It should be done tomorrow.  I'll reply to this thread again once it's done.

**Comment by hakuame** [comment]
Thank you for your work

**Comment by WhatDaPuck** [comment]
I changed a few things around so you should have the ability to change what you need.

If you have any more issues feel free to message me.

https://github.com/WhatDaPuck/NotAnotherAnimeTheme/commit/a74d6128c8cf1a8fdfbf9be97643b669dfd15d2c

**Comment by hakuame** [comment]
Thank you very much, the update works really well!
