### ISSUE TITLE
Black Background after trying to change image

### ISSUE THREAD

**Issue by chewiewhells** [WhatDaPuck/NotAnotherAnimeTheme#6]
The background goes black after trying to change the background image 
![black background](https://user-images.githubusercontent.com/35111826/34577239-6bc89bb6-f14e-11e7-8cb1-a6372d6bb48c.PNG)
![css](https://user-images.githubusercontent.com/35111826/34577282-a3f83d48-f14e-11e7-9a83-db75aca99c9f.PNG)

**Comment by WhatDaPuck** [comment]
This code works for me 
`[class~=app] {
    background: url(https://i.imgur.com/yYKWYjG.jpg) !important;
    background-size: cover !important;
}`

![discordptb_2018-01-04_15-35-08](https://user-images.githubusercontent.com/10362744/34583225-ef7b1fe0-f164-11e7-8176-a983e86f93af.jpg)

**Comment by chewiewhells** [comment]
Copy and pasting the code to had written has worked for me. Thank you very much.
