### ISSUE TITLE
Background isn't displayed in chats

### ISSUE THREAD

**Issue by Emril44** [WhatDaPuck/NotAnotherAnimeTheme#60]
So I just booted up Discord again, and I'm greeted with a grey screen.
![image](https://user-images.githubusercontent.com/42112702/43685379-c3d19308-98ba-11e8-9b02-0c7871ca46c2.png)
Thing is, it's only grey in chats and the Games tab, if I go to my friend list, everything is fine and the background is the one I added.
What should I do?

**Comment by Qu4k3** [comment]
Today we are planning to release a rework that will solve all this recent updates Discord has been making.
If you are not in the discord group, we strongly recommend that you join the server to know when we will publish the update.
I will leave this issue opened since then.

**Comment by Emril44** [comment]
Okay, thanks.
