### ISSUE TITLE
Theme appears all black 

### ISSUE THREAD

**Issue by Leontajnie** [WhatDaPuck/NotAnotherAnimeTheme#7]
Hello, 

I started discord today and suddenly the whole theme is black, I tried to reinstal and resave the file but nothing helps.

![theme](https://user-images.githubusercontent.com/35533425/35049456-5f16acf8-fba0-11e7-8828-f6bc574d5c3a.JPG)

**Comment by NiceLol** [comment]
Same issue here, lemme know if you find a fix

**Comment by WhatDaPuck** [comment]
Fixed in this commit,
https://github.com/WhatDaPuck/NotAnotherAnimeTheme/commit/809e07db760dbd0e315ccbb913ac1736f30b456f

If you have any other issues feel free to open another issue or message me.

**Comment by Leontajnie** [comment]
Thx! :)
