### ISSUE TITLE
:thinking:

### ISSUE THREAD

**Issue by ImPham** [WhatDaPuck/NotAnotherAnimeTheme#9]
![discord_2018-01-20_10-58-35](https://user-images.githubusercontent.com/35625582/35182232-ef58a834-fdd0-11e7-8a6d-ac06ee757aa5.png)
![discord_2018-01-20_10-57-42](https://user-images.githubusercontent.com/35625582/35182233-f2cf7dbc-fdd0-11e7-8dc3-0429b077ace4.png)

**Comment by WhatDaPuck** [comment]
very descriptive issue
